# Generated by Django 2.2.2 on 2019-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=60)),
                ('address', models.CharField(default='', max_length=60)),
                ('state', models.CharField(default='On', max_length=60, null=True)),
                ('notes', models.TextField(null=True)),
                ('num_cpus', models.IntegerField(null=True)),
                ('os', models.CharField(max_length=60, null=True)),
                ('is_vm', models.BooleanField(default=False)),
                ('guest_os', models.CharField(max_length=60, null=True)),
                ('host_os', models.CharField(max_length=60, null=True)),
                ('host_address', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
