# Generated by Django 2.2.2 on 2019-11-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('input_type', models.CharField(default='text', max_length=60)),
                ('display_name', models.CharField(max_length=60)),
                ('model_field_null', models.BooleanField(default=True)),
                ('model_field_type', models.CharField(default='CharField', max_length=60)),
                ('model_field_default_value', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data_type', models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date')], editable=False, max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldDropdownOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='Test Option', max_length=60)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icingahostmanager_app.Field')),
            ],
        ),
    ]
