# Generated by Django 2.2.2 on 2019-10-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='hostname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='guest_os',
            new_name='network_zone',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_address',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_os',
        ),
        migrations.RemoveField(
            model_name='host',
            name='is_vm',
        ),
        migrations.AddField(
            model_name='host',
            name='env',
            field=models.CharField(default='Echo', max_length=60),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(default='Red Hat/RHEL', max_length=60),
        ),
        migrations.AlterField(
            model_name='host',
            name='state',
            field=models.CharField(default='On', max_length=60),
        ),
    ]
