# Generated by Django 2.2.2 on 2019-11-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0002_field_fielddropdownoption_fieldschema_modelschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
