# Generated by Django 2.2.2 on 2019-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0002_auto_20191017_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='checks_to_execute',
            field=models.TextField(null=True),
        ),
    ]
