# Generated by Django 2.2.2 on 2019-10-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0004_host_datacenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cluster',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='disable_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='disable_ssh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='disable_wmi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='http_vhosts',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='process_names',
            field=models.TextField(null=True),
        ),
    ]
