# Generated by Django 2.2.2 on 2019-10-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0006_auto_20191021_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='environment',
            new_name='env',
        ),
    ]
