# Generated by Django 2.2.2 on 2019-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0008_auto_20191021_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='env',
            field=models.CharField(default='Echo', max_length=60),
        ),
    ]
