# Generated by Django 2.2.2 on 2019-10-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0009_auto_20191021_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='check_command',
            field=models.CharField(default='hostalive', max_length=60),
        ),
    ]
