# Generated by Django 2.2.2 on 2019-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0010_host_check_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='zone',
            field=models.CharField(default='IZ-A', max_length=10),
        ),
    ]
