# Generated by Django 2.2.2 on 2019-10-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icingahostmanager_app', '0012_host_template_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ncpa',
            field=models.BooleanField(default=False),
        ),
    ]
